### ISSUE TITLE
Add RxJava support

### ISSUE THREAD

**Issue by keiferstone** [keiferstone/nonet#2]

**Comment by kaushikgopal** [comment]
I wrote this previously as part of a talk i gave but It didn't make it into the talk for want of time. I figured [i'd share the code with you (for inspiration)](https://github.com/kaushikgopal/RxJava-Android-Samples/blob/master/app/src/main/java/com/morihacky/android/rxjava/fragments/NetworkDetectorFragment.java#L65)

**Comment by Jawnnypoo** [comment]
I think having RxJava support is great, but I also think it should either be an optional additional dependency within this library (not required), or it should at least be stated in the README that it uses RxJava or mention how it can be used. Just since at the surface level, people may not realize they are pulling in the RxJava dependency

**Comment by keiferstone** [comment]
@Jawnnypoo just pushed a change that makes the rxjava dependency optional (provided). Now if you want to use Monitor.observe(), you have to include the rxjava dependency in your app's build.gradle. You'll get a compiler error if you  try to call Monitor.observe() without including the rxjava dependency. Pending some testing, I'll try to release this later today.

**Comment by keiferstone** [comment]
I'll update the readme eventually too. I'm just lazy.

**Comment by Jawnnypoo** [comment]
Nice! In my experience, if you use `provided` instead of compile, you will run into some errors when you compile with ProGuard enabled, which can be ignored, but it would be good to note them in the README.  You will have to test it out to see what they are with ProGuard, but more than likely the rule will be `-dontwarn io.reactivex.**`

**Comment by keiferstone** [comment]
Good to know. I'll definitely be doing some ProGuard testing.

Also, TURN DOWN FOR WHAT?!

**Comment by Jawnnypoo** [comment]
![giphy](https://cloud.githubusercontent.com/assets/1459320/22522580/aaff41ee-e881-11e6-99a0-62585b4603bf.gif)
